config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people, :constraints => {:format => 'html'}, except: :show

  resources :clients, :constraints => {:format => 'html'} do
    resources :bills, :constraints => {:format => 'html'}, except: :show
    resources :contact_infos, :constraints => {:format => 'html'}, except: [:show, :index]
  end

  get 'clients/:id/total_billed_amount_of/:year' => 'clients#total_billed_amount'
  get 'clients/:id/amount_of_bills_in/:month' => 'clients#amount_of_bills'

  get 'set_side/:side' => 'application#set_side'
  get 'set_language/:language' => 'application#set_language'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :bills, dependent: :destroy
  has_many :contact_infos, dependent: :destroy

  validates_associated :bills
  validates_associated :contact_infos

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :birthday, presence: true
  validates :gender, presence: true, length: { is: 1 }
  validates :dni, presence: true, numericality: true, length: { minimum: 7, maximum: 8 }
  validates :cuit, presence: true, numericality: true, length: { minimum: 10, maximum: 11 }

  def age
    dob = self.birthday
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def total_billed_amount_collected_in (year)
   @bills = self.bills.select { |bill| bill.issue_date.year == year };
   total_amount_of @bills
  end

  def amount_of_bills_issued_in (month)
    @bills =  self.bills.select { |bill| bill.issue_date.year == Time.now.utc.to_date.year && bill.issue_date.month == month};
    @bills.count
  end

  def most_bills_issued_people
    people = self.bills.map { |b| b.person }.uniq

    @most_billed = []

    people.each do |person|
      total = person.bills.select { |b| b.client.id == self.id }.inject(0.0) { |sum, bill|  bill.total_amount + sum }
      @most_billed << [person, total]
    end

    @most_billed.sort! { |first, second| second.second <=> first.second }
    return @most_billed.first 5
  end

  def total_amount_of (bills)
    bills.inject(0.0) { |sum, bill|  bill.total_amount + sum }
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  #it calls set_client before show, edit, update or destroy action
  before_action :set_client, only: [:show,:edit,:update,:destroy, :total_billed_amount, :amount_of_bills]
  before_action :set_genders, only: [:new, :edit, :show, :create, :update]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/total_billed_amount_of
  def total_billed_amount
    @year = Integer params[:year]
    @amount = @client.total_billed_amount_collected_in @year
    render json: @amount
  end

  # GET /clients/1/amount_of_bills_in
  def amount_of_bills
    @month = Integer params[:month]
    @amount = @client.amount_of_bills_issued_in @month
    render json: @amount
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new (client_params)
    if @client.save
      @contact_info = ContactInfo.new do |c|
          c.name = "email"
          c.value = params[:email]
          c.client_id = @client.id
      end
      if @contact_info.save
        redirect_to @client, notice: t('successfully_created',obj: t('client'))
      end
    else
      @email = params[:email]
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: t('successfully_updated',obj: t('client'))
    else
      #It renders the edit.html.erb template belonging to the same controller.
      render :edit
    end
  end

  # DELETE  /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: t('successfully_destroyed',obj: t('client'))
  end
end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  def set_genders
      @genders = [[t('male'),"M"],[t('female'),"F"]]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:first_name, :last_name, :birthday, :gender, :email, :dni, :cuit)
  end

app/helpers/clients_helper.rb
module ClientsHelper
  def total_billed_amount_client_path
    "/clients/#{@client.id}/total_billed_amount_of/"
  end
  def amount_of_bills_path
    "/clients/#{@client.id}/amount_of_bills_in/"
  end
end

app/views/clients/_form.html.erb
<%= form_for(@client, url: { action: action }) do |f| %>
<% if @client.errors.any? %>
  <div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h2><%= pluralize(@client.errors.count, "error") %>
    <%= t('prohibited_this_from_being_saved', obj: t('client')) %>:</h2>
      <ul>
      <% @client.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <%= notice %>
  </div>
  <script type="text/javascript">
    $( document ).ready(function()
    {
      $('.field_with_errors').css ("display","block");
      $('.field_with_errors').css ("background-color","#eee");
      $('.field_with_errors').css ("border-radius","3px");
    });
  </script>
<% end %>

<h1><%= t(method + '_client') %></h1>

<div class="col-lg-6">
  <div class="well bs-component">
    <form class="form-horizontal">
      <fieldset>
        <div class="container-fluid">
          <legend></legend>

          <%= f.hidden_field :cuit %>

          <div class="row">
            <div class="form-group">
              <%= f.label t('first_name'), class:'col-lg-2 control-label' %>
              <div class="col-lg-10">
                <%= f.text_field :first_name, class:'form-control', placeholder: t('first_name'), required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <%= f.label t('last_name'), class:'col-lg-2 control-label' %>
              <div class="col-lg-10">
                <%= f.text_field :last_name, class:'form-control', placeholder: t('last_name'), required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <%= f.label t('birthday'), class:'col-lg-2 control-label' %>
              <div class="col-lg-10">
                <%= f.date_field :birthday, class:'form-control', placeholder: t('birthday'), required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <%= f.label t('gender'), class:'col-lg-2 control-label' %>
              <div class="col-lg-10">
                <%= f.select :gender, @genders, {}, { class: 'form-control', required: true } %>
              </div>
            </div>
          </div>

          <% if action == "create" %>
          <div class="row">
            <div class="form-group">
              <label class="col-lg-2 control-label" for="client_email"><%= t('Email') %></label>
              <div class="col-lg-10">
                <input class="form-control" placeholder="Email" type="text" name="email" id="client_email" required="true" value="<%= @email %>">
              </div>
            </div>
          </div>
          <% end %>

          <div class="row">
            <div class="form-group">
              <%= f.label t('dni'), class:'col-lg-2 control-label' %>
              <div class="col-lg-10">
                <%= f.text_field :dni, class:'form-control', placeholder: t('dni'), maxlength: "8", required: true %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="form-group col-xs-2">
              <%= f.label t('cuit'), class:' control-label' %>
            </div>
            <div class="form-group col-xs-2">
              <input class="form-control " placeholder="<%= t('type') %>" type="text" id="type_cuit" maxlength="2", required="true">
            </div>
            <div class="form-group col-xs-6">
              <input class="form-control " placeholder="<%= t('number') %>" type="text" id="number_cuit" maxlength="8", required="true">
            </div>
            <div class="form-group col-xs-2">
              <input class="form-control " placeholder="<%= t('verification') %>" type="text" id="verification_cuit" maxlength="1", required="true">
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <div class="col-lg-10 col-lg-offset-2">
                <%= link_to t('cancel'), clients_path, class:"btn btn-default" %>
                <button type="submit" class="btn btn-primary"><%= t('submit') %></button>
              </div>
            </div>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
<% end %>

<script type="text/javascript">

  $( document ).ready(function() {
    setCuitInputs();

    $('.<%= method %>_client').submit (function () {
      setHiddenCuit();
    });

    $('#client_dni').keyup (function () {
      $('#number_cuit').val($('#client_dni').val());
      if ($('#client_dni').val().length == 8)
      {
        calculateCuit ($('#client_dni').val());
      }
    });
  });

  function calculateCuit(dni)
  {
    var gCode = getGenderCode();

    if (gCode == false)
      return;

    setTypeCuit(gCode);

    dni = dni.split("");

    var almostCuit = dni.map(function (x) {
      return parseInt(x, 10);
    });

    almostCuit.unshift(gCode[1]);
    almostCuit.unshift(gCode[0]);

    var mult = [5, 4, 3, 2, 7, 6, 5, 4, 3, 2];
    var total = 0;

    for (var i = 0; i < mult.length; i++)
    {
      total += almostCuit[i] * mult[i];
    }

    var mod = total % 11;
    var verification = mod == 0 ? 0 : mod == 1 ? 9 : 11 - mod;

    setVerificationCuit (verification);
  }

  function getGenderCode ()
  {
    if ($('#client_gender').val() != "")
    {
      if ($('#client_gender').val() == "F")
        return [2,7];
      else
        return [2,0];
    }
    else
    {
      return false;
    }
  }

  function setTypeCuit (genderCode)
  {
    $('#type_cuit').val (genderCode[0].toString() + genderCode[1].toString());
  }

  function setVerificationCuit (verification)
  {
    $('#verification_cuit').val (verification);
  }

  function setHiddenCuit ()
  {
    $('#client_cuit').val ($('#type_cuit').val() + $('#number_cuit').val() + $('#verification_cuit').val());
  }

  function setCuitInputs ()
  {
    if ($('#client_cuit').val () != "")
    {
      var type = $('#client_cuit').val ().substr(0,2);
      var number = $('#client_cuit').val ().substr(2,8);
      var verification = $('#client_cuit').val ().substr(10,1);

      $('#type_cuit').val(type);
      $('#number_cuit').val(number);
      $('#verification_cuit').val(verification);
    }
  }
</script>

app/views/clients/edit.html.erb
<%= render 'form', action:'update', method:'edit' %>

app/views/clients/index.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="col-lg-12">
  <div class="page-header">
    <h1 id="tables"><%= t('listing_clients') %></h1>
  </div>

  <div class="bs-component">
    <table class="table table-striped table-hover ">
      <thead>
      <tr>
        <th><%= t('first_name') %></th>
        <th><%= t('last_name') %></th>
        <th><%= t('date_word') %></th>
        <th><%= t('gender') %></th>
        <th><%= t('dni') %></th>
        <th><%= t('cuit') %></th>
        <th><%= t('email') %></th>
        <th><%= t('bills_issued') %></th>
        <th colspan="4"></th>
      </tr>
      </thead>
      <tbody>
      <% @clients.each do |client| %>
      <% email = client.contact_infos.select { |c| c.name == "email" }[0] %>
          <tr>
            <td><%= client.first_name %></td>
            <td><%= client.last_name %></td>
            <td><%= client.birthday %></td>
            <td><%= client.gender == "F" ? t('female') : t('male') %></td>
            <td><%= client.dni %></td>
            <td><%= client.cuit %></td>
            <td>
            <% unless email.nil? %>
              <%= email.value %>
            <% end %>
            </td>
            <td><%= client.bills.count %></td>
            <td><%= link_to t('more_info'), client %></td>
            <td><%= link_to t('list_bills'), client_bills_path(client) %></td>
            <td><%= link_to t('edit', obj: ""), edit_client_path(client) %></td>
            <td><%= link_to t('destroy'), client, method: :delete, data: { confirm: t('are_you_sure') } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= link_to t('new_client'), new_client_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/clients/new.html.erb
<%= render 'form', action: 'create', method: 'new' %>

app/views/clients/show.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="col-lg-4">

<h1><%= t('client_information', first_name: @client.first_name, last_name: @client.last_name) %></h1>

<table class="table table-striped table-hover ">
  <tbody>
    <tr>
      <td>
        <strong><%= t('first_name') %></strong>
      </td>
      <td>
        <%= @client.first_name %>
      </td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>
        <strong><%= t('last_name') %></strong>
      </td>
      <td>
        <%= @client.last_name %>
      </td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>
        <strong><%= t('birthday') %></strong>
      </td>
      <td>
        <%= @client.birthday %>
      </td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>
        <strong><%= t('age') %></strong>
      </td>
      <td>
        <%= @client.age %>
      </td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>
        <strong><%= t('gender') %></strong>
      </td>
      <td>
        <%= @client.gender == "F" ? t('female') : t('male') %>
      </td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>
        <strong><%= t('dni') %></strong>
      </td>
      <td>
        <%= @client.dni %>
      </td>
      <td colspan="2"></td>
    </tr>
    <tr>
      <td>
        <strong><%= t('cuit') %></strong>
      </td>
      <td>
        <%= @client.cuit %>
      </td>
      <td colspan="2"></td>
    </tr>

      <% for @contact_info in @client.contact_infos %>
        <tr>
          <td>
            <strong><%= @contact_info.name.titleize %></strong>
          </td>
          <td>
            <%= @contact_info.value %>
          </td>
          <td>
            <%= link_to t('edit',obj: ""), edit_client_contact_info_path(@client, @contact_info) %>
          </td>
          <td>
            <%= link_to t('destroy'), client_contact_info_path(@client, @contact_info), method: :delete, data: { confirm: t('are_you_sure') } %>
          </td>
        </tr>
      <% end %>

  </tbody>
</table>

<%= link_to t('new_contact_info'), new_client_contact_info_path(@client), class:"btn btn-primary" %>
<%= link_to t('edit', obj: t('client')), edit_client_path(@client), class:"btn btn-primary" %>
<%= link_to t('back'), clients_path, class:"btn btn-primary" %>

</div>
<div class="col-lg-1">
</div>
<div class="col-lg-6">

<h1><%= t('bills_information') %></h1>

<table class="table table-striped table-hover ">
  <tbody>
    <tr>
      <td class="col-lg-6">
        <strong>
          <%= t('amount_of_bills_issued_in') %>
          <%= select_month(Date.today, {:field_name => 'amountOfBillsSelect'})%>
          <%= Time.now.utc.to_date.year %>
        </strong>
      </td>
      <td>
        <div id="amountOfBills">
           <%= @client.amount_of_bills_issued_in Date.today.month %>
        </div>
      </td>

    </tr>
    <tr>
      <td class="col-lg-6">
        <strong>
          <%= t('total_billed_amount_of') %>
          <%= select_year(Date.today, {:field_name => "totalAmountSelect", :start_year => Date.today.prev_year.year, :end_year => Date.today.next_year.year}) %>
        </strong>
      </td>
      <td>
        <div id="totalAmount">
          $ <%= @client.total_billed_amount_collected_in Date.today.year %>
        </div>
      </td>
    </tr>
    <tr>
      <td class="col-lg-6">
        <strong><%= t('bills_issued') %></strong>
      </td>
      <td>
        <%= @client.bills.count %>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to t('new_bill'), new_client_bill_path(@client), class:"btn btn-primary" %>
<%= link_to t('list_bills'), client_bills_path(@client), class:"btn btn-primary" %>

<% @people_with_amount = @client.most_bills_issued_people %>
<br>
<br>
<h1 id="tables"><%= t('most_bills_issued_people') %></h1>
<div class="bs-component">
  <table class="table table-striped table-hover ">
    <thead>
    <tr>
      <th><%= t('person') %></th>
      <th><%= t('amount') %></th>
    </tr>
    </thead>
    <tbody>
    <%  @people_with_amount.each do |person| %>
        <tr>
          <td><%= person[0].name %></td>
          <td><%= person[1] %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

</div>
<div class="col-lg-1">
</div>

<script type="text/javascript">
  var total_billed_amount_path = "<%= total_billed_amount_client_path %>"
  var amount_of_bills_path = "<%= amount_of_bills_path %>"

  $( document ).ready(function() {
    //Get total billed amount of the selected year
    $('#date_totalAmountSelect').change(function ()
      {
        $.ajax({
          url: total_billed_amount_path + $('#date_totalAmountSelect').val(),
          success: function (data) {
            $('#totalAmount').html("$ "+data);
          }
        });
      });

    //Get amount of bills issued on the selected month
    $('#date_amountOfBillsSelect').change(function ()
      {
        $.ajax({
          url: amount_of_bills_path + $('#date_amountOfBillsSelect').val(),
          success: function (data) {
            $('#amountOfBills').html(data);
          }
        });
      });
  });
</script>