config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people, :constraints => {:format => 'html'}, except: :show

  resources :clients, :constraints => {:format => 'html'} do
    resources :bills, :constraints => {:format => 'html'}, except: :show
    resources :contact_infos, :constraints => {:format => 'html'}, except: [:show, :index]
  end

  get 'clients/:id/total_billed_amount_of/:year' => 'clients#total_billed_amount'
  get 'clients/:id/amount_of_bills_in/:month' => 'clients#amount_of_bills'

  get 'set_side/:side' => 'application#set_side'
  get 'set_language/:language' => 'application#set_language'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
  end

end

app/views/home/index.html.erb
<h1 class="text-center homeText"><%= t('welcome_to_ebilling') %></h1>
<h4 class="text-center text-muted"><%= t('the_evader_billing_system') %></h4>
<br>
<br>
<br>

<% if !cookies[:side].nil? %>
  <h2 class="text-center fontJedi"><%= t('choose_an_action_to_begin') %></h2>
    <div class="div-center col-lg-4">
    <div class="text-center col-lg-4"><%= link_to t('list_clients'), clients_path, class:"btn btn-primary" %></div>
    <div class="text-center col-lg-4"></div>
    <div class="text-center col-lg-4"><%= link_to t('list_people'), people_path,  class:"btn btn-primary" %></div>
  </div>
<% else %>

  <h2 class="text-center fontJedi"><%= t('choose_your_side') %></h2>
    <h4 class="text-center text-muted"><%= t('only_once_you_can_choose') %></h4>
  <br>
  <div class="div-center col-lg-4">
    <div class="text-center col-lg-4"><a href="javascript:selectSide('navbar-info')" class="btn btn-info"><%= t('light_side') %></a></div>
    <div class="text-center col-lg-4"></div>
    <div class="text-center col-lg-4"><a href="javascript:selectSide('navbar-danger')" class="btn btn-danger"><%= t('dark_side') %></a></div>
  </div>

<% end %>
<script type="text/javascript">

  function selectSide (side)
  {
    $.ajax({
      url: <%= side_path %> + side,
      success: function () {
        location.reload();
      }
    });
  }

</script>