config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people, :constraints => {:format => 'html'}, except: :show

  resources :clients, :constraints => {:format => 'html'} do
    resources :bills, :constraints => {:format => 'html'}, except: :show
    resources :contact_infos, :constraints => {:format => 'html'}, except: [:show, :index]
  end

  get 'clients/:id/total_billed_amount_of/:year' => 'clients#total_billed_amount'
  get 'clients/:id/amount_of_bills_in/:month' => 'clients#amount_of_bills'

  get 'set_side/:side' => 'application#set_side'
  get 'set_language/:language' => 'application#set_language'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :client
  belongs_to :person
  validates :total_amount, presence: true, numericality: true
  validates :issue_date, presence: true
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:edit, :update, :destroy]
  before_action :set_people, only: [:new, :edit, :create, :update]
  before_action :set_client, only: [:index, :edit]

  # GET /bills
  def index
    @bills = @client.bills
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    @bill.client = Client.find(params.require (:client_id))
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  def create
    @bill = Bill.new(bill_params)
      if @bill.save
        redirect_to client_bills_path(@bill.client), notice: t('successfully_created',obj: t('bill'))
      else
         render :new
      end
  end

  # PATCH/PUT /bills/1
  def update
      if @bill.update(bill_params)
        redirect_to client_bills_path(@bill.client), notice: t('successfully_updated',obj: t('bill'))
      else
         render :edit
      end
  end

  # DELETE /bills/1
  def destroy
    @bill.destroy
    redirect_to client_bills_path(@bill.client), notice: t('successfully_destroyed',obj: t('bill'))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:client_id, :person_id, :description, :total_amount, :issue_date)
    end

    def set_people
      @people = Person.pluck(:name, :id)
    end

    def set_client
      @client = Client.find(params.require :client_id)
    end
end

app/views/bills/_form.html.erb
<%= form_for([@client,@bill], url: { action: action } ) do |f| %>
<% if @bill.errors.any? %>
<div class="alert alert-dismissable alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h2><%= pluralize(@bill.errors.count, "error") %>
  <%= t('prohibited_this_from_being_saved', obj: t('bill')) %>:</h2>
    <ul>
    <% @bill.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <%= notice %>
</div>
<script type="text/javascript">
  $( document ).ready(function()
  {
    $('.field_with_errors').css ("display","block");
    $('.field_with_errors').css ("background-color","#eee");
    $('.field_with_errors').css ("border-radius","3px");
  });
</script>
<% end %>

<h1><%= t(method + '_bill') %></h1>

<div class="col-lg-6">
  <div class="well bs-component">
    <form class="form-horizontal">
      <fieldset>
        <legend></legend>

        <%= f.hidden_field :client_id %>

        <div class="form-group">
          <%= f.label t('person'), class:'col-lg-2 control-label'  %>
          <div class="col-lg-10">
            <%= f.select :person_id, @people, {}, { class: "form-control", required: true } %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t('issue_date'), class:'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.date_field :issue_date, class:'form-control', placeholder: t('issue_date'), required: true %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t('description'), class:'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_area :description, class:'form-control', rows:3, placeholder: t('description') %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t('total_amount'), class:'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_field :total_amount, class:'form-control', placeholder: t('total_amount'), required: true %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= link_to t('cancel'), client_bills_path, class:"btn btn-default" %>
            <button type="submit" class="btn btn-primary"><%= t('submit') %></button>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
<% end %>

app/views/bills/edit.html.erb
<%= render 'form', action:'update', method: 'edit' %>

app/views/bills/index.html.erb
<% if notice %>
<div class="alert alert-dismissable alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<% end %>

<div class="col-lg-12">
  <div class="page-header">
    <h1 id="tables"><%= t('listing_bills', first_name: @client.first_name, last_name: @client.last_name) %></h1>
  </div>

  <div class="bs-component">
    <table class="table table-striped table-hover ">

      <thead>
        <tr>
          <th><%= t('client') %></th>
          <th><%= t('person') %></th>
          <th><%= t('description') %></th>
          <th><%= t('total_amount') %></th>
          <th><%= t('issue_date') %></th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @bills.each do |bill| %>
          <tr>
            <td><%= bill.client.first_name %> <%= bill.client.last_name %></td>
            <td><%= bill.person.name %></td>
            <td><%= bill.description %></td>
            <td><%= bill.total_amount %></td>
            <td><%= bill.issue_date %></td>
            <td><%= link_to t('edit',obj: ""), edit_client_bill_path(@client,bill) %></td>
            <td><%= link_to t('destroy'), client_bill_path(@client, bill), method: :delete, data: { confirm: t('are_you_sure') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to t('new_bill'), new_client_bill_path, class:"btn btn-primary" %>
<%= link_to t('back_to', first_name: @client.first_name, last_name: @client.last_name), client_path(@client), class:"btn btn-primary" %>

app/views/bills/new.html.erb
<%= render 'form', action: 'create', method: 'new' %>